#cloud-config
users:
  - name: ansible
    shell: /bin/bash    
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIARbj7O9ZqhYpTS/dVJs7KQoULBbwNAmehG+xZLFbNdv ed25519-key-20221030"