---
apiVersion: v1
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1IjogewoJCQkiYXV0aCI6ICJjM1JrTFRBd09TMHdORGM2UjJRNEttWmtZVFUyIgoJCX0sCgkJImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsKCQkJImF1dGgiOiAiYzNSa0xUQXdPUzB3TkRjNlIyUTRLbVprWVRVMiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson