# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-vault-secret
    app.kubernetes.io/instance: "prod-store"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-vault-secret-{{ .Chart.Version }}"
    app.kubernetes.io/component: vault-secret
    app.kubernetes.io/part-of: sausage-store
data:
  vault_token: aHZzLkNBRVNJSjJITTR6M1cyQW5qWlRyYzVqUU1hYkFqOFFXdGNxekhrRHZyN2FYOGxBdEdoNEtIR2gyY3k1dmFGSkNaVmR2UWt3M01EVTBhWEZrUTJ4emExbEJUVmc=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-docker-secret
    app.kubernetes.io/instance: "prod-store"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-ingress-{{ .Chart.Version }}"
    app.kubernetes.io/component: docker-vault-secret
    app.kubernetes.io/part-of: sausage-store
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1IjogewoJCQkiYXV0aCI6ICJjM1JrTFRBd09TMHdORGM2UjJRNEttWmtZVFUyIgoJCX0sCgkJImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsKCQkJImF1dGgiOiAiYzNSa0xUQXdPUzB3TkRjNlIyUTRLbVprWVRVMiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson

# Секрет, необходимый, для подключения к БД backend-report
---
apiVersion: v1
kind: Secret
metadata:
  name: db
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-db-secret
    app.kubernetes.io/instance: "prod-store"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-db-secret-{{ .Chart.Version }}"
    app.kubernetes.io/component: db-secret
    app.kubernetes.io/part-of: sausage-store
data:
  db: bW9uZ29kYjovL2FwZXJtYW5zdGQ6VGVzdHVzcjEyMzRAcmMxYS1tenMwbmR5bjJyeDB2d3c3Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvYXBlcm1hbnN0ZD90bHM9dHJ1ZSZyZXBsaWNhU2V0PXJzMDEmdGxzQWxsb3dJbnZhbGlkQ2VydGlmaWNhdGVzPXRydWUmdGxzQ0FGaWxlPVlhbmRleEludGVybmFsUm9vdENBLmNydA==
type: Opaque