---
apiVersion: v1
kind: Secret
metadata:
  name: db
  labels:
    app: vault
data:               
  db: bW9uZ29kYjovL2FwZXJtYW46VGVzdHVzcjEyMzRAcmMxYi1jbmV1ZDNtNmNyenNkZGlhLm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvYXBlcm1hbj90bHM9dHJ1ZSZyZXBsaWNhU2V0PXJzMDEmdGxzQWxsb3dJbnZhbGlkQ2VydGlmaWNhdGVzPXRydWUmdGxzQ0FGaWxlPVlhbmRleEludGVybmFsUm9vdENBLmNydA==
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
