# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLkNBRVNJSjhpRVNUOGo4bGR6SVpNTDFrMUdwaWlfT2RhVjgwRGpOdlJVR0hFeXpqX0doNEtIR2gyY3k0ME5XNXZkbGRwZFdadmQwWldiRkpuWkhKdlFVRk9ZMnc=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1IjogewoJCQkiYXV0aCI6ICJjM1JrTFRBd09TMHdORGM2UjJRNEttWmtZVFUyIgoJCX0sCgkJImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsKCQkJImF1dGgiOiAiYzNSa0xUQXdPUzB3TkRjNlIyUTRLbVprWVRVMiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
